source ~/env.z.sh
source ~/.files/zsh/config.z.sh
source ~/.files/zsh/colors.z.sh
source ~/.files/zsh/plugins/mac.z.sh
source ~/.files/zsh/dir.z.sh
source ~/.files/zsh/alias/mac.z.sh
source ~/.files/zsh/docker.z.sh
source ~/.files/zsh/projects/mac.z.sh
source ~/.files/zsh/source/mac.z.sh
source ~/.files/zsh/tmux.z.sh
source ~/.files/zsh/git.z.sh
source ~/.files/zsh/personal/mac.z.sh
source ~/.files/zsh/session.z.sh
source ~/.files/zsh/todo.z.sh